### PR TITLE
feat: add results.json and ResultPage.js

### PR DESCRIPTION
**Pull request by eun5young**
Please feel free to let me know if there is anything to change!! ^^!!

### CODE REVIEW

**Comment by kimm00** [comment]
Please change the code in English~. This is very good!

**Comment by eun5young** [comment]
Okay! I will edit it in English! Thank you for letting me know~

**Comment by eun5young** [comment]
I modified it to English. Please check it out!

**Comment by kimm00** [comment]
> I modified it to English. Please check it out!

I got it. :)

**Pull request merged**
